---

geometry:
    DecFanAng: 0.9643345
    ScanR: 538.52
    Radius: 154
    Number: 984
    YL: 835

data:
    input_path: './data/projection/ProjectionCurve.mat'
    save_path: './data/reconstruction/ReconCurve.mat'

dll:
    dll_path: './dll/Fbp.dll'
