---

geometry:
    DecFanAng: 0.9643345
    ScanR: 538.52
    Radius: 154
    Number: 984
    YL: 835

data:
    input_path: './data/projection/projection_curve.mat'
    save_path: './data/reconstruction/recon_curve.mat'

dll:
    dll_path: './dll/fbp.dll'
